import type { Metadata } from "next";
import {
    Inter as FontSans,
    Open_Sans,
    Source_Code_Pro,
    Source_Sans_3
} from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";
import LoadingScreen from "@/components/screens/loading";
import Footer from "@/components/layout/footer";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans"
});

const fontMono = Source_Sans_3({
    subsets: ["latin"],
    variable: "--font-mono"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    fontSans.variable,
                    fontMono.variable
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    storageKey="theme"
                >
                    {children}
                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    );
}
